#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

env:
  global:
    - API_URL="https://" API_KEY="xxx" DEBTOR_NUMBER="000000" VERSION="v0"

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm config set quecom-internal-shop:apiUrl=$API_URL
  - npm config set quecom-internal-shop:apiKey=$API_KEY
  - npm config set quecom-internal-shop:debtorNumber=$DEBTOR_NUMBER
  - npm config set quecom-internal-shop:version=$VERSION
  - npm run config
  - ng build --environment=prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change